dist: trusty

sudo: required

language: cpp
os:
    - linux
compiler:
    - clang
    - gcc

env:
    - TARGET_CPU=amd64 BUILD_CONFIGURATION=Debug
    - TARGET_CPU=amd64 BUILD_CONFIGURATION=Release
    - TARGET_CPU=x86 BUILD_CONFIGURATION=Debug
    - TARGET_CPU=x86 BUILD_CONFIGURATION=Release
    - EXAMPLE_PATH=Examples/example.py

addons:
  apt:
    packages:
      - valgrind
      - cppcheck

script:
  - cmake .
  - cppcheck src/* include/* tests/* --enable=all --check-config
  - make
  - valgrind --check-leaks=full --track_origins=yes ./testTask1 ${EXAMPLE_PATH}