dist: trusty

sudo: required

language: cpp
os:
    - linux
compiler:
    - clang
    - gcc

env:
    - TARGET_CPU=amd64 BUILD_CONFIGURATION=Debug
    - TARGET_CPU=amd64 BUILD_CONFIGURATION=Release
    - TARGET_CPU=x86 BUILD_CONFIGURATION=Debug
    - TARGET_CPU=x86 BUILD_CONFIGURATION=Release

addons:
  apt:
    packages:
      - valgrind
      - cppcheck
  snaps:
    - name: cmake
      confinement: classic
      channel: 3.18/candidate

script:
  - cmake .
  - cppcheck src/* include* --enable=all --check-config
  - make Task1